# Generated by Django 3.2.5 on 2021-07-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Action', '0002_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroin_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=100)),
                ('h_age', models.IntegerField()),
                ('h_email', models.EmailField(max_length=100)),
                ('h_password', models.CharField(max_length=30)),
                ('h_manager', models.CharField(max_length=100)),
            ],
        ),
    ]
