# Generated by Django 3.2.5 on 2021-07-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Action', '0003_heroin_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_mobileno', models.IntegerField(max_length=10)),
                ('c_email', models.EmailField(max_length=40)),
                ('c_gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('c_complaint', models.CharField(max_length=2000)),
            ],
        ),
    ]
